#!/bin/bash
echo "whats the name ??"
###just a simple .sh file maker#### 
read NAME
touch $NAME.sh
sudo chmod u+x -vf $NAME.sh
sudo sh ./ $NAME.sh
mv $NAME.sh $NAME
crontab -e $NAME
echo "done bitchhh!!!"


