#!/bin/bash
sudo -s << EOF
apt modernize-sources -y
apt -f install 
apt update -y --allow-change-held-packages --install-recommends --fix-missing
apt upgrade -y --unattended-upgrade=yes --allow-change-held-packages --install-recommends
apt full-upgrade
apt dist-upgrade
apt autoremove -y 
EOF
